### ISSUE TITLE
#featureRequest - making callback for `off` as optional

### ISSUE THREAD

**Issue by gokatz** [BBVAEngineering/ember-web-workers#5]
Can we make the callback for the `off` handler as optional?

**Use case:** 
May not need to track out the callback handler between `on` and `off` of a worker

**How**
if there is not callback, then we can filter out all the worker (by name) and terminate

**Comment by josex2r** [comment]
It seems ok to me 👍, can you open a pull-request with the changes?
Be sure to follow our guidelines (eslint, testing, coding style, ...) to be able to merge with the master branch.

**Comment by gokatz** [comment]
Will raise a PR with the changes

**Comment by gokatz** [comment]
Changes merged with #6 and hance closing.
