### ISSUE TITLE
Is it possible to use this with promise-worker?

### ISSUE THREAD

**Issue by NullVoxPopuli** [BBVAEngineering/ember-web-workers#59]
I was looking at the promise-worker readme, and it looks like you need to pass the worker instance to the promise worker wrapper -- and since this library proxy's worker access via service, It's not clear to me how ember-web-workers would work with promise-worker: https://github.com/nolanlawson/promise-worker

**Comment by adrigzr** [comment]
Hi, I think you won't need that lib. We already _promisify_ the worker under the worker service.

```
// Some Ember context.
{
  foo() {
    return this.get('worker').postMessage('test', { foo: 'bar' }).then((response) => {
        // response => { bar: 'bar' }
      }, (error) => {
        // error contains the message thrown by the worker.
      });
  }
}
```

**Comment by NullVoxPopuli** [comment]
thanks!
