### ISSUE TITLE
Is it worth combining efforts with https://github.com/srowhani/ember-artisans ?

### ISSUE THREAD

**Issue by NullVoxPopuli** [BBVAEngineering/ember-web-workers#60]
Just came across https://github.com/srowhani/ember-artisans
in my search for typescript capabilities with web-workers -- they have an interesting interface, and I'm wondering what tradeoffs may be? maybe efforts can be combined between this project and that project?

Looking at the implementation, though. It looks like some combination of the behaviors of ember-web-workers + promise-worker + a decorator for accessing worker instances?

**Comment by adrigzr** [comment]
Hi, I think both projects (this and ember-artisans) do same things but with different API. You should choose whatever you prefer. 

We don't transpile the worker source, so  you can't use typescript there =/

**Comment by NullVoxPopuli** [comment]
Thanks!
